[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
ajose = "6F6jhojAyf5ksvSpERBUwFKnBXSR5DUdcCxThDdSZgta"

[programs.devnet]
ajose = "6F6jhojAyf5ksvSpERBUwFKnBXSR5DUdcCxThDdSZgta"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
