[package]
name = "tests"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"
rust-version = "1.89.0"

[dependencies]
ajose = { version = "0.1.0", path = "../programs/ajose" }
anchor-lang = "0.32.1"
litesvm = "0.7.0"
solana-sdk = "2.3.0"
spl-associated-token-account = "7.0.0"
spl-token = "8.0.0"
